
USE [Teste]
GO
IF OBJECT_ID('dbo.P_CFOP') IS NOT NULL
BEGIN
    DROP PROCEDURE dbo.P_CFOP
    IF OBJECT_ID('dbo.P_CFOP') IS NOT NULL
        PRINT '<<< FALHA APAGANDO A PROCEDURE dbo.P_CFOP >>>'
END
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON 
GO 
CREATE PROCEDURE dbo.P_CFOP 
AS
BEGIN
	SELECT
	Cfop,
	Total_BaseICMS = ISNULL(SUM(BaseIcms), 0),
	Total_ICMS = ISNULL(SUM(ValorIcms), 0),
	Total_BaseIPI = ISNULL(SUM(BaseIpi), 0),
	Total_IPI = ISNULL(SUM(ValorIPI), 0)
	FROM NotaFiscalItem
	GROUP BY Cfop
END
GO